In [1]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from datetime import datetime

today = datetime.today().strftime('%Y-%m-%d')

ROOT_PROJECT = Path.cwd().parent
SRC = ROOT_PROJECT / 'src'
CHECKPOINT = ROOT_PROJECT / 'Data' / 'checkpoints'

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from utils.analyze import (
    get_sizes_groups,
    describe_clusters,
    describe_clusters_median
)

KMeansDrainLogs = CHECKPOINT / f'drain_logs-{today}' / 'Kmeans_ver2'
print(f'Ruta para inicializar el proyecto: {KMeansDrainLogs}')

def detect_friendly_bot(user_agent, bot_patterns):
    ua = str(user_agent).lower()
    for bot_name, patterns in bot_patterns.items():
        for pattern in patterns:
            if pattern.lower() in ua:
                return bot_name
    return None

Ruta para inicializar el proyecto: /Users/marcoantoniogarciamartinez/Documents/Python Local/Proyectos/EntregableTec/Data/checkpoints/drain_logs-2026-07-27/Kmeans_ver2

## Analizis de KMeans n

In [2]:
X_drains = pd.read_parquet(str(KMeansDrainLogs))

In [3]:
X_drains['kmeans_labels'].unique()

array([3, 1, 5, 0, 4, 2], dtype=int32)

In [4]:
sizes_drains = get_sizes_groups(X_drains, kind = 'kmeans_labels')
sizes_drains

   kmeans_labels  tamano  porcentajes
0              0     374       0.0748
1              1    3379       0.6758
2              2      58       0.0116
3              3     390       0.0780
4              4     106       0.0212
5              5     693       0.1386

In [5]:
X_groups = get_sizes_groups(X_drains, kind = 'kmeans_labels')
X_groups

   kmeans_labels  tamano  porcentajes
0              0     374       0.0748
1              1    3379       0.6758
2              2      58       0.0116
3              3     390       0.0780
4              4     106       0.0212
5              5     693       0.1386

In [6]:
X_describe_clusters_drains = describe_clusters(X_drains, kind = 'kmeans_labels')
X_describe_clusters_drains

kmeans_labels,0,1,2,3,4,5
routes_visited,2.12,1.00,53.45,5.47,13.92,2.33
unique_routes,2.07,1.00,53.36,5.35,13.70,2.26
activity_window_ms,1720.61,0.01,476358.84,296415.15,340490.11,202128.85
mean_time_between_requests_ms,1519.37,0.01,10514.59,72157.44,29127.73,163965.47
median_time_between_requests_ms,1503.07,0.01,6031.16,55431.70,15336.42,163736.01
is_one_shot,0.00,1.00,0.00,0.00,0.00,0.00
dbscan_labels,5.41,0.99,2.38,3.67,-0.15,2.35
agglomerative_labels,3.63,3.00,2.00,0.00,0.83,1.00

In [7]:
X_describe_clusters_drains.to_json()

'{"0":{"routes_visited":2.12,"unique_routes":2.07,"activity_window_ms":1720.61,"mean_time_between_requests_ms":1519.37,"median_time_between_requests_ms":1503.07,"is_one_shot":0.0,"dbscan_labels":5.41,"agglomerative_labels":3.63},"1":{"routes_visited":1.0,"unique_routes":1.0,"activity_window_ms":0.01,"mean_time_between_requests_ms":0.01,"median_time_between_requests_ms":0.01,"is_one_shot":1.0,"dbscan_labels":0.99,"agglomerative_labels":3.0},"2":{"routes_visited":53.45,"unique_routes":53.36,"activity_window_ms":476358.84,"mean_time_between_requests_ms":10514.59,"median_time_between_requests_ms":6031.16,"is_one_shot":0.0,"dbscan_labels":2.38,"agglomerative_labels":2.0},"3":{"routes_visited":5.47,"unique_routes":5.35,"activity_window_ms":296415.15,"mean_time_between_requests_ms":72157.44,"median_time_between_requests_ms":55431.7,"is_one_shot":0.0,"dbscan_labels":3.67,"agglomerative_labels":0.0},"4":{"routes_visited":13.92,"unique_routes":13.7,"activity_window_ms":340490.11,"mean_time_between_requests_ms":29127.73,"median_time_between_requests_ms":15336.42,"is_one_shot":0.0,"dbscan_labels":-0.15,"agglomerative_labels":0.83},"5":{"routes_visited":2.33,"unique_routes":2.26,"activity_window_ms":202128.85,"mean_time_between_requests_ms":163965.47,"median_time_between_requests_ms":163736.01,"is_one_shot":0.0,"dbscan_labels":2.35,"agglomerative_labels":1.0}}'

In [8]:
view_drains = X_drains[X_drains['kmeans_labels'] == 3]

view_drains = view_drains.sort_values(by = 'routes_visited', ascending=True)
view_drains.head(20)

,time_window,routes_visited,unique_routes,activity_window_ms,mean_time_between_requests_ms,median_time_between_requests_ms,is_one_shot,ja4Digest,proxy.userAgent,proxy.clientIp,kmeans_labels,dbscan_labels,agglomerative_labels
86329,2026-06-11 01:00:00+00:00,4,4,469544,156514.666667,130119.0,False,t13d311200_e8f1e7e78f70_6077d120928a,ias-va/3.3 (former https://www.admantx.com + h...,162.211.125.8,3,9,0
28542,2026-06-09 19:20:00+00:00,4,4,285718,95239.333333,92364.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,162.120.186.188,3,9,0
1219,2026-06-09 04:20:00+00:00,4,4,267280,89093.333333,37519.0,False,t13d101000_61a7ad8aa9b6_f9531d972513,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",18.97.9.99,3,17,0
11096,2026-06-08 22:10:00+00:00,4,4,361518,120506.000000,60943.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,162.120.185.225,3,9,0
11610,2026-06-08 22:50:00+00:00,4,4,455700,151900.000000,202696.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,162.120.186.163,3,9,0
62418,2026-06-09 05:50:00+00:00,4,4,240936,80312.000000,120209.0,False,t13d181300_e8a523a41297_43ade6aba3df,Mediapartners-Google,72.14.199.237,3,9,0
49759,2026-06-10 23:10:00+00:00,4,4,355177,118392.333333,151985.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,162.120.186.97,3,9,0
62882,2026-06-09 10:50:00+00:00,4,4,211934,70644.666667,40770.0,False,t13d181300_e8a523a41297_43ade6aba3df,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...,66.249.79.227,3,-1,0
48031,2026-06-10 20:50:00+00:00,4,4,16771,5590.333333,397.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,187.190.170.204,3,-1,0
73874,2026-06-11 04:40:00+00:00,4,4,302918,100972.666667,134647.0,False,t13d2212h2_231e334592e8_36bf25f296df,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",52.167.144.195,3,9,0
10813,2026-06-08 21:50:00+00:00,4,4,465871,155290.333333,203685.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,72.14.201.212,3,9,0
31341,2026-06-09 22:00:00+00:00,4,4,465804,155268.000000,196484.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,162.120.186.161,3,9,0
43337,2026-06-10 15:50:00+00:00,4,4,397949,132649.666667,84214.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,162.120.185.227,3,9,0
56127,2026-06-09 15:30:00+00:00,4,4,15577,5192.333333,2193.0,False,t13d1517h2_8daaf6152771_b6f405a00624,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,200.68.185.22,3,-1,0
46858,2026-06-10 19:30:00+00:00,4,4,343109,114369.666667,95952.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,162.120.185.226,3,9,0
77254,2026-06-09 23:10:00+00:00,4,4,302397,100799.000000,131952.0,False,t13d301100_1d37bd780c83_4df47d6b5700,IAS Crawler (ias_crawler; http://integralads.c...,3.217.168.199,3,9,0
66002,2026-06-10 20:50:00+00:00,4,4,47039,15679.666667,13751.0,False,t13d181300_e8a523a41297_43ade6aba3df,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...,66.249.79.227,3,-1,0
28607,2026-06-09 19:30:00+00:00,4,4,320201,106733.666667,104056.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,162.120.186.97,3,9,0
26827,2026-06-09 17:50:00+00:00,4,4,312960,104320.000000,77909.0,False,t13d1516h2_8daaf6152771_d8a2da3f94cd,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,162.120.186.162,3,9,0
69500,2026-06-10 01:10:00+00:00,4,4,364424,121474.666667,302.0,False,t13d2013h2_a09f3c656075_7f0f34a4126d,Mozilla/5.0 (iPhone; CPU iPhone OS 26_5_0 like...,200.68.170.3,3,-1,0

## Analisis de pipeline de DBSCAN

In [9]:
dbscan_analyze = get_sizes_groups(X_drains, kind = 'dbscan_labels')
X_describe_clusters_drains_dbscan = describe_clusters(X_drains, kind = 'dbscan_labels')

In [10]:
dbscan_analyze

    dbscan_labels  tamano  porcentajes
0              -1     421       0.0842
1               0      42       0.0084
2               1    3368       0.6736
3               2     453       0.0906
4               3     157       0.0314
5               4      31       0.0062
6               5       6       0.0012
7               6     293       0.0586
8               7      30       0.0060
9               8      44       0.0088
10              9      77       0.0154
11             10      18       0.0036
12             11      10       0.0020
13             12       6       0.0012
14             13       8       0.0016
15             14       6       0.0012
16             15       5       0.0010
17             16       5       0.0010
18             17       5       0.0010
19             18       7       0.0014
20             19       5       0.0010
21             20       3       0.0006

In [11]:
X_describe_clusters_drains_dbscan

dbscan_labels,-1,0,1,2,3,4,5,6,7,8,...,11,12,13,14,15,16,17,18,19,20
routes_visited,12.44,5.00,1.0,2.00,3.00,3.00,3.00,2.00,7.00,6.00,...,8.00,2.0,2.00,10.00,5.00,4.00,4.00,56.43,2.0,53.33
unique_routes,12.12,5.00,1.0,2.00,3.00,3.00,3.00,2.00,7.00,6.00,...,8.00,2.0,2.00,10.00,5.00,4.00,4.00,56.43,1.0,53.33
activity_window_ms,210006.81,427392.74,0.0,191217.06,291602.90,65093.16,958.67,1244.19,457572.30,427934.68,...,489165.40,35.0,142.38,509024.50,253383.00,167756.00,279388.00,588983.29,70034.0,590423.33
mean_time_between_requests_ms,29399.52,106848.18,0.0,191217.06,145801.45,32546.58,479.33,1244.19,76262.05,85586.94,...,69880.77,35.0,142.38,56558.28,63345.75,55918.67,93129.33,10628.56,70034.0,11281.92
median_time_between_requests_ms,15884.68,91644.95,0.0,191217.06,145801.45,32546.58,479.33,1244.19,62505.88,63115.02,...,60232.00,35.0,142.38,50980.67,43949.80,56084.20,34962.60,10519.14,70034.0,10493.33
is_one_shot,0.00,0.00,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
kmeans_labels,2.90,3.00,1.0,5.00,5.00,5.00,0.00,0.00,3.00,3.00,...,3.00,0.0,0.00,4.00,3.00,3.00,3.00,2.00,5.0,2.00
agglomerative_labels,0.91,0.00,3.0,1.00,1.00,1.00,4.00,3.89,0.00,0.00,...,0.00,4.0,4.00,0.00,0.00,0.00,0.00,2.00,1.0,2.00

In [12]:
X_describe_clusters_drains_dbscan.to_json()

'{"-1":{"routes_visited":12.44,"unique_routes":12.12,"activity_window_ms":210006.81,"mean_time_between_requests_ms":29399.52,"median_time_between_requests_ms":15884.68,"is_one_shot":0.0,"kmeans_labels":2.9,"agglomerative_labels":0.91},"0":{"routes_visited":5.0,"unique_routes":5.0,"activity_window_ms":427392.74,"mean_time_between_requests_ms":106848.18,"median_time_between_requests_ms":91644.95,"is_one_shot":0.0,"kmeans_labels":3.0,"agglomerative_labels":0.0},"1":{"routes_visited":1.0,"unique_routes":1.0,"activity_window_ms":0.0,"mean_time_between_requests_ms":0.0,"median_time_between_requests_ms":0.0,"is_one_shot":1.0,"kmeans_labels":1.0,"agglomerative_labels":3.0},"2":{"routes_visited":2.0,"unique_routes":2.0,"activity_window_ms":191217.06,"mean_time_between_requests_ms":191217.06,"median_time_between_requests_ms":191217.06,"is_one_shot":0.0,"kmeans_labels":5.0,"agglomerative_labels":1.0},"3":{"routes_visited":3.0,"unique_routes":3.0,"activity_window_ms":291602.9,"mean_time_between_requests_ms":145801.45,"median_time_between_requests_ms":145801.45,"is_one_shot":0.0,"kmeans_labels":5.0,"agglomerative_labels":1.0},"4":{"routes_visited":3.0,"unique_routes":3.0,"activity_window_ms":65093.16,"mean_time_between_requests_ms":32546.58,"median_time_between_requests_ms":32546.58,"is_one_shot":0.0,"kmeans_labels":5.0,"agglomerative_labels":1.0},"5":{"routes_visited":3.0,"unique_routes":3.0,"activity_window_ms":958.67,"mean_time_between_requests_ms":479.33,"median_time_between_requests_ms":479.33,"is_one_shot":0.0,"kmeans_labels":0.0,"agglomerative_labels":4.0},"6":{"routes_visited":2.0,"unique_routes":2.0,"activity_window_ms":1244.19,"mean_time_between_requests_ms":1244.19,"median_time_between_requests_ms":1244.19,"is_one_shot":0.0,"kmeans_labels":0.0,"agglomerative_labels":3.89},"7":{"routes_visited":7.0,"unique_routes":7.0,"activity_window_ms":457572.3,"mean_time_between_requests_ms":76262.05,"median_time_between_requests_ms":62505.88,"is_one_shot":0.0,"kmeans_labels":3.0,"agglomerative_labels":0.0},"8":{"routes_visited":6.0,"unique_routes":6.0,"activity_window_ms":427934.68,"mean_time_between_requests_ms":85586.94,"median_time_between_requests_ms":63115.02,"is_one_shot":0.0,"kmeans_labels":3.0,"agglomerative_labels":0.0},"9":{"routes_visited":4.0,"unique_routes":4.0,"activity_window_ms":369513.42,"mean_time_between_requests_ms":123171.14,"median_time_between_requests_ms":121089.71,"is_one_shot":0.0,"kmeans_labels":3.0,"agglomerative_labels":0.0},"10":{"routes_visited":2.0,"unique_routes":2.0,"activity_window_ms":10223.72,"mean_time_between_requests_ms":10223.72,"median_time_between_requests_ms":10223.72,"is_one_shot":0.0,"kmeans_labels":1.94,"agglomerative_labels":1.0},"11":{"routes_visited":8.0,"unique_routes":8.0,"activity_window_ms":489165.4,"mean_time_between_requests_ms":69880.77,"median_time_between_requests_ms":60232.0,"is_one_shot":0.0,"kmeans_labels":3.0,"agglomerative_labels":0.0},"12":{"routes_visited":2.0,"unique_routes":2.0,"activity_window_ms":35.0,"mean_time_between_requests_ms":35.0,"median_time_between_requests_ms":35.0,"is_one_shot":0.0,"kmeans_labels":0.0,"agglomerative_labels":4.0},"13":{"routes_visited":2.0,"unique_routes":2.0,"activity_window_ms":142.38,"mean_time_between_requests_ms":142.38,"median_time_between_requests_ms":142.38,"is_one_shot":0.0,"kmeans_labels":0.0,"agglomerative_labels":4.0},"14":{"routes_visited":10.0,"unique_routes":10.0,"activity_window_ms":509024.5,"mean_time_between_requests_ms":56558.28,"median_time_between_requests_ms":50980.67,"is_one_shot":0.0,"kmeans_labels":4.0,"agglomerative_labels":0.0},"15":{"routes_visited":5.0,"unique_routes":5.0,"activity_window_ms":253383.0,"mean_time_between_requests_ms":63345.75,"median_time_between_requests_ms":43949.8,"is_one_shot":0.0,"kmeans_labels":3.0,"agglomerative_labels":0.0},"16":{"routes_visited":4.0,"unique_routes":4.0,"activity_window_ms":167756.0,"mean_time_between_requests_ms":55918.67,"median_time_between_requests_ms":56084.2,"is_one_shot":0.0,"kmeans_labels":3.0,"agglomerative_labels":0.0},"17":{"routes_visited":4.0,"unique_routes":4.0,"activity_window_ms":279388.0,"mean_time_between_requests_ms":93129.33,"median_time_between_requests_ms":34962.6,"is_one_shot":0.0,"kmeans_labels":3.0,"agglomerative_labels":0.0},"18":{"routes_visited":56.43,"unique_routes":56.43,"activity_window_ms":588983.29,"mean_time_between_requests_ms":10628.56,"median_time_between_requests_ms":10519.14,"is_one_shot":0.0,"kmeans_labels":2.0,"agglomerative_labels":2.0},"19":{"routes_visited":2.0,"unique_routes":1.0,"activity_window_ms":70034.0,"mean_time_between_requests_ms":70034.0,"median_time_between_requests_ms":70034.0,"is_one_shot":0.0,"kmeans_labels":5.0,"agglomerative_labels":1.0},"20":{"routes_visited":53.33,"unique_routes":53.33,"activity_window_ms":590423.33,"mean_time_between_requests_ms":11281.92,"median_time_between_requests_ms":10493.33,"is_one_shot":0.0,"kmeans_labels":2.0,"agglomerative_labels":2.0}}'

## Agglomerative CLuster Labels

In [13]:
agglomerative_analyze = get_sizes_groups(X_drains, kind = 'agglomerative_labels')
X_describe_clusters_drains_agglo = describe_clusters(X_drains, kind = 'agglomerative_labels')

In [14]:
agglomerative_analyze

   agglomerative_labels  tamano  porcentajes
0                     0     456       0.0912
1                     1     734       0.1468
2                     2     102       0.0204
3                     3    3379       0.6758
4                     4     329       0.0658

In [15]:
X_describe_clusters_drains_agglo

agglomerative_labels                     0          1          2     3       4
routes_visited                        6.16       2.33      38.37  1.00    2.07
unique_routes                         6.02       2.25      38.27  1.00    2.05
activity_window_ms               297266.79  191231.53  429398.55  0.01  988.52
mean_time_between_requests_ms     66363.66  155139.00   15557.24  0.01  955.66
median_time_between_requests_ms   50033.48  154922.35    7676.68  0.01  953.61
is_one_shot                           0.00       0.00       0.00  1.00    0.00
kmeans_labels                         3.11       4.72       2.86  1.00    0.00
dbscan_labels                         3.20       2.43       0.92  0.99    5.69

In [16]:
X_describe_clusters_drains_agglo.to_json()

'{"0":{"routes_visited":6.16,"unique_routes":6.02,"activity_window_ms":297266.79,"mean_time_between_requests_ms":66363.66,"median_time_between_requests_ms":50033.48,"is_one_shot":0.0,"kmeans_labels":3.11,"dbscan_labels":3.2},"1":{"routes_visited":2.33,"unique_routes":2.25,"activity_window_ms":191231.53,"mean_time_between_requests_ms":155139.0,"median_time_between_requests_ms":154922.35,"is_one_shot":0.0,"kmeans_labels":4.72,"dbscan_labels":2.43},"2":{"routes_visited":38.37,"unique_routes":38.27,"activity_window_ms":429398.55,"mean_time_between_requests_ms":15557.24,"median_time_between_requests_ms":7676.68,"is_one_shot":0.0,"kmeans_labels":2.86,"dbscan_labels":0.92},"3":{"routes_visited":1.0,"unique_routes":1.0,"activity_window_ms":0.01,"mean_time_between_requests_ms":0.01,"median_time_between_requests_ms":0.01,"is_one_shot":1.0,"kmeans_labels":1.0,"dbscan_labels":0.99},"4":{"routes_visited":2.07,"unique_routes":2.05,"activity_window_ms":988.52,"mean_time_between_requests_ms":955.66,"median_time_between_requests_ms":953.61,"is_one_shot":0.0,"kmeans_labels":0.0,"dbscan_labels":5.69}}'

K-Means fue seleccionado como modelo principal porque produjo seis grupos diferenciados, interpretables y manejables para revisión humana. Los grupos distinguen sesiones de una sola solicitud, actividad mínima rápida, actividad reducida pero espaciada, navegación moderada, navegación alta y navegación intensiva. Agglomerative Clustering encontró una estructura general muy semejante, confirmando la existencia de estos perfiles, aunque condensó algunos niveles de actividad. DBSCAN identificó patrones locales más específicos, pero generó una cantidad elevada de microclusters y observaciones consideradas ruido, lo que reduce su utilidad para un proceso de revisión humana.